[package]
name = "RustySync"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.32"
notify = "8.0.0"
blake3 = "1.6.1"
actix-web = "4.10.2"
serde = "1.0.219"
serde_json = "1.0.140"
rusqlite = {features = ["bundled"], version = "0.35.0"}
chrono = "0.4.41"
walkdir = "2.5.0"
